name: Tag Release

on:
  push:
    branches: [main]
    paths: [pyproject.toml]

permissions:
  contents: write

jobs:
  call-tag-release:
    uses: django-mvp/shared/.github/workflows/tag-release.yml@v0.6.0
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
